# Generated by Django 5.0.4 on 2024-05-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_category_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
