# Generated by Django 5.0.4 on 2024-05-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='productoss',
        ),
    ]
